### ISSUE TITLE
runtime error: slice bounds out of range & invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tokox** [Arapak/sio-tool#7]
W trakcie testowania mojego rozwiązania do zadania `bud` z `oi31-1` na `sio2-mimuw` na [tej paczce testów](https://drive.google.com/file/d/1H5hNILjGyEKGq5cD63d7-Zpo747dJgG9/view?usp=sharing) wystąpił poniższy błąd:
```
Passed #bud3710.in ... 0.000s 2.215MB
Passed #bud37098.in ... 0.000s 2.215MB
Passed #bud37102.in ... 0.000s 2.215MB
Passed #bud37105.in ... 0.000s 2.215MB
Passed #bud37106.in ... 0.000s 2.215MB
Passed #bud37103.in ... 0.000s 2.215MB
Passed #bud37109.in ... 0.000s 2.215MB
Passed #bud37107.in ... 0.000s 2.215MB
Passed #bud37101.in ... 0.000s 2.215MB
Passed #bud37104.in ... 0.000s 2.215MB
Passed #bud37110.in ... 0.000s 2.215MB
Passed #bud37111.in ... 0.000s 2.215MB
Passed #bud3711.in ... 0.000s 2.215MB
Passed #bud37112.in ... 0.000s 2.215MB
Passed #bud37113.in ... 0.000s 2.215MB
Passed #bud37108.in ... 0.000s 2.215MB
Passed #bud37117.in ... 0.000s 2.215MB
Passed #bud37116.in ... 0.000s 2.215MB
Passed #bud37115.in ... 0.000s 2.215MB
Passed #bud37118.in ... 0.000s 2.215MB
Passed #bud3712.in ... 0.000s 2.215MB
Passed #bud37120.in ... 0.000s 2.215MB
Passed #bud37114.in ... 0.000s 2.215MB
Passed #bud37121.in ... 0.000s 2.215MB
Passed #bud37119.in ... 0.000s 2.215MB
Passed #bud37122.in ... 0.000s 2.215MB
Passed #bud37123.in ... 0.000s 2.215MB
Passed #bud37124.in ... 0.000s 2.215MB
Passed #bud37127.in ... 0.000s 2.215MB
TESTS RAN: 30143 MAX TIME: 0.109s MAX MEMORY: 2.215MB OK: 30143panic: runtime error: slice bounds out of range [:1425] with capacity 512

goroutine 33 [running]:
bytes.Index({0xc002964600, 0x600, 0x200}, {0xc00008d960, 0x70, 0x70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/bytes.go:1255 +0x48a
bytes.Contains(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/bytes.go:76
github.com/Arapak/sio-tool/judge.RunProcess({0xc001ff9560, 0x114}, {0xb19360?, 0xc002f02830}, 0xc002f02838)
	/home/runner/work/sio-tool/sio-tool/judge/process.go:73 +0x4e5
github.com/Arapak/sio-tool/judge.RunProcessWithOiejq({0xc0040b6030, 0x7}, {0xb19360, 0xc002f02830}, 0xc0040be000)
	/home/runner/work/sio-tool/sio-tool/judge/oiejq.go:118 +0x32e
github.com/Arapak/sio-tool/judge.Judge({0xc0026e6690?, 0x4001b80000000000?}, {0xc0026e67d0, 0x42}, {0xc0011201c6, 0xb}, {0xc0040b6030, 0x7}, 0xc0040be000)
	/home/runner/work/sio-tool/sio-tool/judge/judge.go:17 +0x12b
github.com/Arapak/sio-tool/cmd.PackageTest.func3(0x1?)
	/home/runner/work/sio-tool/sio-tool/cmd/packageTest.go:251 +0x3c6
created by github.com/Arapak/sio-tool/cmd.PackageTest
	/home/runner/work/sio-tool/sio-tool/cmd/packageTest.go:236 +0x6af
[tomasz@fedora bud]$ 
```
Kiedy włączyłem `st package_test` jeszcze raz, żeby sprawdzić czy to nie było przypadkiem i może jednak zadziała nie wywaliło się na tym błędzie tylko na poniższym:
```
Passed #bud6306.in ... 0.000s 2.215MB
Passed #bud63066.in ... 0.000s 2.215MB
Passed #bud63068.in ... 0.000s 2.215MB
Passed #bud63065.in ... 0.000s 2.215MB
Passed #bud63062.in ... 0.000s 2.215MB
Passed #bud6307.in ... 0.000s 2.215MB
Passed #bud63072.in ... 0.000s 2.215MB
Passed #bud63069.in ... 0.000s 2.215MB
Passed #bud63070.in ... 0.000s 2.215MB
Passed #bud63067.in ... 0.000s 2.215MB
Passed #bud63074.in ... 0.000s 2.215MB
Passed #bud63071.in ... 0.000s 2.215MB
Passed #bud63075.in ... 0.000s 2.215MB
Passed #bud63073.in ... 0.000s 2.215MB
Passed #bud63076.in ... 0.000s 2.215MB
Passed #bud63078.in ... 0.000s 2.215MB
Passed #bud63077.in ... 0.000s 2.215MB
Passed #bud63079.in ... 0.000s 2.215MB
Passed #bud6308.in ... 0.000s 2.215MB
Passed #bud63081.in ... 0.000s 2.215MB
Passed #bud63080.in ... 0.000s 2.215MB
Passed #bud63082.in ... 0.000s 2.215MB
Passed #bud63084.in ... 0.000s 2.215MB
Passed #bud63083.in ... 0.000s 2.215MB
Passed #bud63085.in ... 0.000s 2.215MB
Passed #bud63087.in ... 0.000s 2.215MB
Passed #bud63086.in ... 0.000s 2.215MB
Passed #bud63088.in ... 0.000s 2.215MB
TESTS RAN: 58990 MAX TIME: 0.109s MAX MEMORY: 2.215MB OK: 58990panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503d4e]

goroutine 50 [running]:
bytes.Index({0x0, 0x200, 0x200}, {0xc003127960, 0x70, 0x70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/bytes.go:1254 +0x20e
bytes.Contains(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/bytes.go:76
github.com/Arapak/sio-tool/judge.RunProcess({0xc00350c360, 0x113}, {0xb19360?, 0xc0000a2c78}, 0xc0000a2c80)
	/home/runner/work/sio-tool/sio-tool/judge/process.go:73 +0x4e5
github.com/Arapak/sio-tool/judge.RunProcessWithOiejq({0xc00302e030, 0x7}, {0xb19360, 0xc0000a2c78}, 0xc003032000)
	/home/runner/work/sio-tool/sio-tool/judge/oiejq.go:118 +0x32e
github.com/Arapak/sio-tool/judge.Judge({0xc0012ea320?, 0x4001b80000000000?}, {0xc0012eab90, 0x42}, {0xc00212e6c6, 0xb}, {0xc00302e030, 0x7}, 0xc003032000)
	/home/runner/work/sio-tool/sio-tool/judge/judge.go:17 +0x12b
github.com/Arapak/sio-tool/cmd.PackageTest.func3(0x0?)
	/home/runner/work/sio-tool/sio-tool/cmd/packageTest.go:251 +0x3c6
created by github.com/Arapak/sio-tool/cmd.PackageTest
	/home/runner/work/sio-tool/sio-tool/cmd/packageTest.go:236 +0x6af
[tomasz@fedora bud]$ 
```
Ponieważ błędy nie powtarzają się po powtórnym uruchomieniu programu, spodziewam się, że gdzieś coś jest nie zdefiniowane (np. Jakaś niezainicjowana zmienna lub brak odpowiedniej synchronizacji wątków (nie znam `go` za bardzo więc nie wiem co to może być)).

**Comment by Arapak** [comment]
Czy w najnowszej wersji błąd dalej występuje?

**Comment by tokox** [comment]
Włączyłem jeszcze raz na wszystkich testach i nie napotkałem błędu, więc można na razie uznać za rozwiązane. Jeśli spotka mnie coś takiego jeszcze raz to dam znać. Issue zamykam.
